networks:
  nextchat-network:

services:
  nextchat:
    image: na2cucl4/nextchat:latest
    container_name: nextchat
    ports:
      - 127.0.0.1:3001:3000
    networks:
      - nextchat-network
    environment:
      BASE_URL: <azure-endpoint>/openai
      OPENAI_API_KEY: <azure-api-key>
      CODE: <code>
      CUSTOM_MODELS: -all,+gpt-5.4@OpenAI,+gpt-5.3-chat@OpenAI,+gpt-5.2@OpenAI,+gpt-5.2-chat@OpenAI,+gpt-5.1@OpenAI,+gpt-5.1-chat@OpenAI,+gpt-5@OpenAI,+gpt-5-mini@OpenAI,+gpt-5-nano@OpenAI,+gpt-5-chat@OpenAI,gpt-image-1.5@OpenAI,gpt-image-1@OpenAI,gpt-image-1-mini@OpenAI
      DEFAULT_MODEL: gpt-5.4@OpenAI
      FILE_READING_SERVER: http://nextchat-readfile:8000/read_file
      HIDE_USER_API_KEY: 1
    restart: always

  nextchat-readfile:
    image: na2cucl4/nextchat-readfile:latest
    container_name: nextchat-readfile
    expose:
      - 8000
    networks:
      - nextchat-network
    restart: always
